services:
  web:
    build:
      context: .
    image: ayansid2323/movie-recommendation:latest
    container_name: movieapp
    ports:
      - "8000:8000"
    develop:
      watch:
        - action: sync
          path: .
          target: /code
    restart: unless-stopped
    networks:
      - my_network

networks:
  my_network:
    name: my_network
    driver: bridge
