services:
  web:
    build: .
    container_name: movieapp
    ports:
      - "8000:8000"
    develop:
      watch:
        - action: sync
          path: .
          target: /code
    restart: always
    networks:
      - my_network

networks:
  my_network:
    name: my_network
    external: true