services:
  web:
    build:
      context: .
    image: ayansid2323/movie-recommendation:latest
    ports:
      - "8996:8000"
    restart: unless-stopped
    networks:
      - my_network

networks:
  my_network:
    name: my_network
    driver: bridge
